# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: tremble
name: signalfx
version: 0.1.3
readme: README.md
authors:
  - Mark Chappell (github.com/tremble)
description:  Ansible collection for managing Splunk SignalFX
license_file: LICENSE
tags:
  - splunk
  - signalfx
repository: https://github.com/tremble/tremble-signalfx
homepage: https://github.com/tremble/tremble-signalfx
issues: https://github.com/tremble/tremble-signalfx/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
